
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-version: 0
    table: TEMPERATURE_API_FLYWAY_SCHEMA_HISTORY
mqtt:
  url: ${MQTT_URL}
  topics: ${MQTT_TOPICS}

server-control:
  whitelist:
    - cs2-dedicated
temperature:
  log-temperature: true
logging:
  level:
    club.mascotfan.temperature_api.club.mascotfan.home-api.MessageHandlerService: DEBUG
    club.mascotfan.temperature_api.config.club.mascotfan.home-api.config.MqttConfig: TRACE
    com.ibasco.agql.core.util.Option: WARN