
CREATE TABLE TEMPERATURES (
    ID SERIAL PRIMARY KEY,
    SOURCE VARCHAR(50) NOT NULL,
    TEMPERATURE_CELSIUS DOUBLE PRECISION NOT NULL,
    RECORDED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE HUMIDITY (
    ID SERIAL PRIMARY KEY,
    SOURCE VARCHAR(50) NOT NULL,
    HUMIDITY_PERCENTAGE DOUBLE PRECISION NOT NULL,
    RECORDED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_temperatures_recorded_at ON temperatures (source, recorded_at);
CREATE INDEX idx_humidity_recorded_at ON humidity (source, recorded_at);